/* This source file is generated by 'makedefs'.  Do not edit. */
#define BUILD_DATE "Sun Jun  2 10:54:09 2019"
#define BUILD_TIME (1559444049UL)

#define VERSION_NUMBER 0x03060200UL
#define VERSION_FEATURES 0x00060040UL
#define IGNORED_FEATURES 0x18080000UL
#define VERSION_SANITY1 0x211c617eUL
#define VERSION_SANITY2 0x148c24958UL
#define VERSION_SANITY3 0x00028000UL

#define VERSION_STRING "3.6.2"
#define VERSION_ID \
 "Unix NetHack Version 3.6.2 - last build Sun Jun  2 10:54:09 2019."
#define COPYRIGHT_BANNER_C \
 "         Version 3.6.2 Unix, built Jun  2 10:54:09 2019."

